# Generated by Django 3.1.7 on 2023-05-27 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('work_order_number', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.PositiveIntegerField()),
                ('start_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('work_type', models.IntegerField(choices=[(0, 'Cleaning'), (1, 'Maid Request'), (2, 'Technician Request'), (3, 'Amenity Request')], default=0)),
                ('work_status', models.IntegerField(choices=[(0, 'Created'), (1, 'Assigned'), (2, 'In Progress'), (3, 'Done'), (4, 'Cancel'), (5, 'Cancel by guest')], default=0)),
                ('assigned_to', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmenityRequest',
            fields=[
                ('workorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work_manager.workorder')),
                ('amenity_request_list', models.JSONField()),
            ],
            bases=('work_manager.workorder',),
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('workorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work_manager.workorder')),
            ],
            bases=('work_manager.workorder',),
        ),
        migrations.CreateModel(
            name='MaidRequest',
            fields=[
                ('workorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work_manager.workorder')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=('work_manager.workorder',),
        ),
        migrations.CreateModel(
            name='TechnicianRequest',
            fields=[
                ('workorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='work_manager.workorder')),
                ('defect_type', models.IntegerField(choices=[(0, 'Electricity'), (1, 'AC'), (2, 'Plumbing'), (3, 'Internet')])),
            ],
            bases=('work_manager.workorder',),
        ),
    ]
