# Generated by Django 3.1.7 on 2023-05-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='work_order_nuber',
            new_name='work_order_number',
        ),
    ]
